name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Initialize DocFX
        run: docfx init -q

      - name: Generate Metadata
        run: docfx metadata

      - name: Build Documentation Site
        run: docfx build

      - name: Publish Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          destination_dir: docs
