name: Release Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Pack NuGet Package
        run: dotnet pack Bank.Domain/Bank.Domain.csproj -o output -c Release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
